-- Clean up old active sets to avoid duplication
UPDATE public.screening_question_sets SET is_active = false;

-- Ensure domains exist (using ON CONFLICT DO UPDATE on slug to make it robust)
DO $$
DECLARE
  fs_id UUID;
  ai_id UUID;
  fe_id UUID;
  be_id UUID;
  cs_id UUID;
  ds_id UUID;
  set_id UUID;
BEGIN
  -- Upsert Domains
  INSERT INTO public.domains (name, description, slug, is_active) VALUES 
  ('Full Stack Development', 'End-to-end web application development', 'full-stack-development', true)
  ON CONFLICT (slug) DO UPDATE SET is_active = true, name = EXCLUDED.name RETURNING id INTO fs_id;

  INSERT INTO public.domains (name, description, slug, is_active) VALUES 
  ('Artificial Intelligence', 'AI, Machine Learning, and Deep Learning', 'artificial-intelligence', true)
  ON CONFLICT (slug) DO UPDATE SET is_active = true, name = EXCLUDED.name RETURNING id INTO ai_id;

  INSERT INTO public.domains (name, description, slug, is_active) VALUES 
  ('Frontend Development', 'UI/UX, React, CSS, and browser-based technologies', 'frontend-development', true)
  ON CONFLICT (slug) DO UPDATE SET is_active = true, name = EXCLUDED.name RETURNING id INTO fe_id;

  INSERT INTO public.domains (name, description, slug, is_active) VALUES 
  ('Backend Development', 'Server-side logic, databases, and APIs', 'backend-development', true)
  ON CONFLICT (slug) DO UPDATE SET is_active = true, name = EXCLUDED.name RETURNING id INTO be_id;

  INSERT INTO public.domains (name, description, slug, is_active) VALUES 
  ('Cybersecurity', 'Network security, ethical hacking, and cryptography', 'cybersecurity', true)
  ON CONFLICT (slug) DO UPDATE SET is_active = true, name = EXCLUDED.name RETURNING id INTO cs_id;

  INSERT INTO public.domains (name, description, slug, is_active) VALUES 
  ('Data Science', 'Data analysis, statistics, and data visualization', 'data-science', true)
  ON CONFLICT (slug) DO UPDATE SET is_active = true, name = EXCLUDED.name RETURNING id INTO ds_id;

  -- 1. Full Stack Development
  -- D1
  INSERT INTO public.screening_question_sets (domain_id, difficulty_level, version, is_active) VALUES (fs_id, 1, 1, true) RETURNING id INTO set_id;
  INSERT INTO public.screening_questions (set_id, type, content, options, correct_answer, explanation) VALUES
  (set_id, 'MCQ', 'Which HTML element is used for the largest heading?', '["<h1>", "<heading>", "<h6>", "<head>"]'::jsonb, '<h1>', 'The <h1> to <h6> tags are used to define HTML headings. <h1> defines the most important heading.'),
  (set_id, 'MCQ', 'Which property is used in CSS to change the background color?', '["color", "bgcolor", "background-color", "bg"]'::jsonb, 'background-color', 'The background-color property sets the background color of an element.'),
  (set_id, 'MCQ', 'Inside which HTML element do we put JavaScript?', '["<script>", "<js>", "<scripting>", "<javascript>"]'::jsonb, '<script>', 'The <script> tag is used to embed a client-side script.'),
  (set_id, 'MCQ', 'What does CSS stand for?', '["Cascading Style Sheets", "Colorful Style Sheets", "Computer Style Sheets", "Creative Style Sheets"]'::jsonb, 'Cascading Style Sheets', 'CSS stands for Cascading Style Sheets, used for describing the presentation of a document.'),
  (set_id, 'MCQ', 'Which is the correct CSS syntax?', '["body {color: black;}", "{body:color=black;}", "body:color=black;", "{body;color:black;}"]'::jsonb, 'body {color: black;}', 'A CSS rule-set consists of a selector and a declaration block enclosed in braces.'),
  (set_id, 'MCQ', 'How do you write "Hello World" in an alert box in JavaScript?', '["msg(''Hello World'');", "alertBox(''Hello World'');", "alert(''Hello World'');", "msgBox(''Hello World'');"]'::jsonb, 'alert(''Hello World'');', 'The alert() method displays an alert box with a specified message and an OK button.'),
  (set_id, 'MCQ', 'Which HTML attribute specifies an alternate text for an image?', '["alt", "title", "src", "longdesc"]'::jsonb, 'alt', 'The alt attribute provides alternative text for an image if the user cannot view it.');

  -- D2
  INSERT INTO public.screening_question_sets (domain_id, difficulty_level, version, is_active) VALUES (fs_id, 2, 1, true) RETURNING id INTO set_id;
  INSERT INTO public.screening_questions (set_id, type, content, options, correct_answer, explanation) VALUES
  (set_id, 'MCQ', 'What is the purpose of the "useEffect" hook in React?', '["To manage local component state", "To handle side effects like data fetching", "To route between pages", "To define context"]'::jsonb, 'To handle side effects like data fetching', 'The useEffect Hook allows you to perform side effects in your components, such as fetching data.'),
  (set_id, 'MCQ', 'Which HTTP method is traditionally used to update an existing resource entirely?', '["GET", "POST", "PUT", "PATCH"]'::jsonb, 'PUT', 'PUT is used to replace all current representations of the target resource with the request payload.'),
  (set_id, 'MCQ', 'What does CORS stand for?', '["Cross-Origin Resource Sharing", "Cross-Origin Routing System", "Centralized Object Reference System", "Cascading Origin Request System"]'::jsonb, 'Cross-Origin Resource Sharing', 'CORS allows restricted resources on a web page to be requested from another domain.'),
  (set_id, 'MCQ', 'Which keyword is used to handle asynchronous operations in Modern JavaScript?', '["async/await", "fetch/catch", "try/catch", "promise/resolve"]'::jsonb, 'async/await', 'async and await make promises easier to write and read.'),
  (set_id, 'MCQ', 'In a relational database, what does a FOREIGN KEY do?', '["Encrypts a column", "Ensures referential integrity between two tables", "Speeds up search queries", "Automatically increments values"]'::jsonb, 'Ensures referential integrity between two tables', 'A FOREIGN KEY is a field (or collection of fields) in one table, that refers to the PRIMARY KEY in another table.'),
  (set_id, 'MCQ', 'Which of the following is NOT a valid JSON data type?', '["Object", "Array", "Function", "String"]'::jsonb, 'Function', 'JSON supports strings, numbers, booleans, null, arrays, and objects, but not functions.'),
  (set_id, 'MCQ', 'What is the main difference between SQL and NoSQL?', '["SQL uses tables, NoSQL uses documents or key-value pairs", "NoSQL is older", "SQL cannot handle large data", "NoSQL requires strict schemas"]'::jsonb, 'SQL uses tables, NoSQL uses documents or key-value pairs', 'SQL databases are table-based, while NoSQL databases are document, key-value, graph, or wide-column stores.');

  -- D3
  INSERT INTO public.screening_question_sets (domain_id, difficulty_level, version, is_active) VALUES (fs_id, 3, 1, true) RETURNING id INTO set_id;
  INSERT INTO public.screening_questions (set_id, type, content, options, correct_answer, explanation) VALUES
  (set_id, 'MCQ', 'Which technique prevents SQL Injection?', '["Prepared Statements (Parameterized Queries)", "Base64 Encoding", "Minifying JavaScript", "Disabling CORS"]'::jsonb, 'Prepared Statements (Parameterized Queries)', 'Prepared statements ensure that parameters are treated as data, not as executable code.'),
  (set_id, 'MCQ', 'What is the purpose of JWT (JSON Web Tokens)?', '["Database indexing", "Stateless authentication and authorization", "Encrypting passwords", "Caching static assets"]'::jsonb, 'Stateless authentication and authorization', 'JWT is an open standard that defines a compact and self-contained way for securely transmitting information between parties as a JSON object.'),
  (set_id, 'MCQ', 'In microservices architecture, what is an API Gateway?', '["A firewall preventing DDOS", "A single entry point that routes client requests to backend services", "A relational database instance", "A load balancer for the frontend"]'::jsonb, 'A single entry point that routes client requests to backend services', 'An API Gateway sits between the clients and the services, providing routing, composition, and translation.'),
  (set_id, 'MCQ', 'What does ACID stand for in database transactions?', '["Atomicity, Consistency, Isolation, Durability", "Array, Cache, Index, Data", "Asynchronous, Concurrent, Isolated, Distributed", "Automatic, Centralized, Integrated, Dynamic"]'::jsonb, 'Atomicity, Consistency, Isolation, Durability', 'ACID properties guarantee that database transactions are processed reliably.'),
  (set_id, 'MCQ', 'What is the role of a reverse proxy like Nginx?', '["To compile React code", "To sit behind a firewall and forward client requests to backend servers", "To manage state in the browser", "To store user sessions"]'::jsonb, 'To sit behind a firewall and forward client requests to backend servers', 'A reverse proxy retrieves resources on behalf of a client from one or more servers.'),
  (set_id, 'MCQ', 'How does React''s Virtual DOM improve performance?', '["By bypassing the browser engine", "By batching and minimizing direct manipulation of the actual DOM", "By executing in a web worker", "By using WebAssembly"]'::jsonb, 'By batching and minimizing direct manipulation of the actual DOM', 'The Virtual DOM allows React to do its computations and find the most efficient way to update the browser''s DOM.'),
  (set_id, 'MCQ', 'Which hashing algorithm is considered secure for storing passwords?', '["MD5", "SHA-1", "Argon2", "Base64"]'::jsonb, 'Argon2', 'Argon2 is a memory-hard password hashing function designed to resist GPU cracking.');

  -- 2. Artificial Intelligence
  -- D1
  INSERT INTO public.screening_question_sets (domain_id, difficulty_level, version, is_active) VALUES (ai_id, 1, 1, true) RETURNING id INTO set_id;
  INSERT INTO public.screening_questions (set_id, type, content, options, correct_answer, explanation) VALUES
  (set_id, 'MCQ', 'What is Machine Learning?', '["A database system", "Algorithms that improve automatically through experience", "A web framework", "A programming language"]'::jsonb, 'Algorithms that improve automatically through experience', 'Machine learning is a subset of AI that enables systems to learn from data without explicit programming.'),
  (set_id, 'MCQ', 'Which language is most commonly used for AI and ML?', '["Java", "Python", "C#", "Ruby"]'::jsonb, 'Python', 'Python is the dominant language in AI/ML due to its rich ecosystem of libraries like Scikit-learn, TensorFlow, and PyTorch.'),
  (set_id, 'MCQ', 'What does NLP stand for?', '["Natural Language Processing", "Neural Logic Programming", "Network Learning Protocol", "New Linear Process"]'::jsonb, 'Natural Language Processing', 'NLP gives machines the ability to read, understand, and derive meaning from human languages.'),
  (set_id, 'MCQ', 'Which of these is a supervised learning task?', '["Clustering", "Dimensionality Reduction", "Image Classification", "Anomaly Detection"]'::jsonb, 'Image Classification', 'Image classification requires labeled data, making it a supervised learning task.'),
  (set_id, 'MCQ', 'What is a Neural Network inspired by?', '["The biological brain", "Computer hardware", "Mathematical matrices", "Quantum mechanics"]'::jsonb, 'The biological brain', 'Neural networks are loosely modeled on the human brain''s architecture of neurons and synapses.'),
  (set_id, 'MCQ', 'Which library is commonly used for tabular data manipulation in Python?', '["TensorFlow", "Pandas", "PyTorch", "Flask"]'::jsonb, 'Pandas', 'Pandas is a fast, powerful, flexible, and easy-to-use open-source data analysis and manipulation tool.'),
  (set_id, 'MCQ', 'What is the target variable in a regression problem?', '["A discrete category", "A continuous numerical value", "A boolean", "An image"]'::jsonb, 'A continuous numerical value', 'Regression models predict continuous numerical outcomes.');

  -- D2
  INSERT INTO public.screening_question_sets (domain_id, difficulty_level, version, is_active) VALUES (ai_id, 2, 1, true) RETURNING id INTO set_id;
  INSERT INTO public.screening_questions (set_id, type, content, options, correct_answer, explanation) VALUES
  (set_id, 'MCQ', 'What does a Convolutional Neural Network (CNN) primarily excel at?', '["Processing tabular data", "Processing sequential data like text", "Processing spatial data like images", "Reinforcement learning"]'::jsonb, 'Processing spatial data like images', 'CNNs are designed to process pixel data and are highly effective for image recognition tasks.'),
  (set_id, 'MCQ', 'What is the purpose of an activation function?', '["To initialize weights", "To introduce non-linearity into the network", "To calculate the loss", "To prevent overfitting"]'::jsonb, 'To introduce non-linearity into the network', 'Activation functions allow neural networks to learn complex, non-linear mappings between inputs and outputs.'),
  (set_id, 'MCQ', 'What is Overfitting?', '["When a model performs poorly on training data", "When a model learns the noise in training data and performs poorly on unseen data", "When the dataset is too large", "When training is too fast"]'::jsonb, 'When a model learns the noise in training data and performs poorly on unseen data', 'Overfitting occurs when a model memorizes the training data rather than generalizing the underlying patterns.'),
  (set_id, 'MCQ', 'Which technique is commonly used to prevent overfitting?', '["Increasing model complexity", "Removing hidden layers", "Dropout", "Using a smaller dataset"]'::jsonb, 'Dropout', 'Dropout randomly ignores a subset of neurons during training, forcing the network to learn robust features.'),
  (set_id, 'MCQ', 'What is Gradient Descent?', '["A data preprocessing method", "An optimization algorithm used to minimize the loss function", "A clustering technique", "A metric for accuracy"]'::jsonb, 'An optimization algorithm used to minimize the loss function', 'Gradient descent iteratively adjusts parameters to find the minimum of a cost function.'),
  (set_id, 'MCQ', 'Which of these is an unsupervised learning algorithm?', '["Linear Regression", "Logistic Regression", "Random Forest", "K-Means Clustering"]'::jsonb, 'K-Means Clustering', 'K-Means partitions data into clusters without relying on labeled outcomes.'),
  (set_id, 'MCQ', 'What does the F1 score measure?', '["The speed of the model", "The harmonic mean of precision and recall", "The absolute error", "The variance of the dataset"]'::jsonb, 'The harmonic mean of precision and recall', 'F1 score balances precision and recall, especially useful for imbalanced datasets.');

  -- D3
  INSERT INTO public.screening_question_sets (domain_id, difficulty_level, version, is_active) VALUES (ai_id, 3, 1, true) RETURNING id INTO set_id;
  INSERT INTO public.screening_questions (set_id, type, content, options, correct_answer, explanation) VALUES
  (set_id, 'MCQ', 'What is the core mathematical operation in the Attention Mechanism of Transformers?', '["Max Pooling", "Scaled Dot-Product", "Sigmoid Activation", "Batch Normalization"]'::jsonb, 'Scaled Dot-Product', 'The scaled dot-product computes the similarity between queries and keys to generate attention weights.'),
  (set_id, 'MCQ', 'What problem does the LSTM architecture solve in Recurrent Neural Networks?', '["Overfitting", "Vanishing Gradient Problem", "High dimensionality", "Class imbalance"]'::jsonb, 'Vanishing Gradient Problem', 'LSTMs use gates to regulate information flow, effectively mitigating the vanishing gradient problem in long sequences.'),
  (set_id, 'MCQ', 'In a Generative Adversarial Network (GAN), what are the two competing networks?', '["Encoder and Decoder", "Actor and Critic", "Generator and Discriminator", "Teacher and Student"]'::jsonb, 'Generator and Discriminator', 'The generator creates fake data, and the discriminator tries to distinguish it from real data.'),
  (set_id, 'MCQ', 'What does Transfer Learning involve?', '["Transferring data to a cloud server", "Taking a pre-trained model and fine-tuning it on a new, related task", "Converting Python code to C++", "Training a model from scratch every time"]'::jsonb, 'Taking a pre-trained model and fine-tuning it on a new, related task', 'Transfer learning leverages features learned from a massive dataset on a smaller, related dataset.'),
  (set_id, 'MCQ', 'What is the purpose of Batch Normalization?', '["To normalize the input dataset before training", "To stabilize and accelerate training by normalizing the inputs of each layer", "To reduce the size of the model", "To increase the learning rate indefinitely"]'::jsonb, 'To stabilize and accelerate training by normalizing the inputs of each layer', 'Batch norm reduces internal covariate shift, allowing for higher learning rates and faster convergence.'),
  (set_id, 'MCQ', 'Which loss function is typically used for multi-class classification?', '["Mean Squared Error", "Binary Cross-Entropy", "Categorical Cross-Entropy", "Huber Loss"]'::jsonb, 'Categorical Cross-Entropy', 'Categorical cross-entropy measures the performance of a classification model where the output is a probability value between 0 and 1 across multiple classes.'),
  (set_id, 'MCQ', 'In reinforcement learning, what does the Bellman Equation describe?', '["The loss gradient", "The relationship between the value of a state and the values of its successor states", "The policy network", "The reward function"]'::jsonb, 'The relationship between the value of a state and the values of its successor states', 'The Bellman equation decomposes the value of a state into immediate reward plus discounted future value.');

  -- 3. Frontend Development
  -- D1
  INSERT INTO public.screening_question_sets (domain_id, difficulty_level, version, is_active) VALUES (fe_id, 1, 1, true) RETURNING id INTO set_id;
  INSERT INTO public.screening_questions (set_id, type, content, options, correct_answer, explanation) VALUES
  (set_id, 'MCQ', 'Which HTML tag is used to create a hyperlink?', '["<a>", "<link>", "<href>", "<nav>"]'::jsonb, '<a>', 'The <a> tag defines a hyperlink, which is used to link from one page to another.'),
  (set_id, 'MCQ', 'What does CSS primarily control?', '["Data storage", "Server routing", "Presentation and layout of a web page", "Database queries"]'::jsonb, 'Presentation and layout of a web page', 'CSS dictates how HTML elements are displayed on screen, paper, or in other media.'),
  (set_id, 'MCQ', 'Which JavaScript method selects an element by its ID?', '["querySelector()", "getElementById()", "getElementsByClassName()", "select()"]'::jsonb, 'getElementById()', 'document.getElementById() returns the element that has the ID attribute with the specified value.'),
  (set_id, 'MCQ', 'Which CSS property makes text bold?', '["font-weight", "text-style", "font-style", "boldness"]'::jsonb, 'font-weight', 'The font-weight property sets how thick or thin characters in text should be displayed.'),
  (set_id, 'MCQ', 'What does DOM stand for?', '["Document Object Model", "Data Object Memory", "Digital Object Mode", "Document Orientation Module"]'::jsonb, 'Document Object Model', 'The DOM represents the page so that programs can change the document structure, style, and content.'),
  (set_id, 'MCQ', 'Which of the following is a CSS preprocessor?', '["HTML5", "React", "Sass", "jQuery"]'::jsonb, 'Sass', 'Sass is a CSS preprocessor that adds features like variables, nested rules, and mixins.'),
  (set_id, 'MCQ', 'How do you add a comment in HTML?', '["// Comment", "/* Comment */", "<!-- Comment -->", "# Comment"]'::jsonb, '<!-- Comment -->', 'HTML comments are written using the <!-- --> syntax.');

  -- D2
  INSERT INTO public.screening_question_sets (domain_id, difficulty_level, version, is_active) VALUES (fe_id, 2, 1, true) RETURNING id INTO set_id;
  INSERT INTO public.screening_questions (set_id, type, content, options, correct_answer, explanation) VALUES
  (set_id, 'MCQ', 'What is CSS Flexbox primarily used for?', '["Adding animations", "Creating 1-dimensional layouts", "Creating 2-dimensional grid layouts", "Styling text"]'::jsonb, 'Creating 1-dimensional layouts', 'Flexbox is designed for laying out items in a single dimension (either a row or a column).'),
  (set_id, 'MCQ', 'In React, what are "props"?', '["Internal component state", "HTML attributes", "Arguments passed into React components", "CSS styles"]'::jsonb, 'Arguments passed into React components', 'Props (properties) are read-only arguments passed from a parent component to a child component.'),
  (set_id, 'MCQ', 'What is Event Bubbling in JavaScript?', '["When an event triggers on a parent and bubbles down to children", "When an event triggers on an element and then on all of its ancestors", "A way to cancel events", "Creating visual bubbles on click"]'::jsonb, 'When an event triggers on an element and then on all of its ancestors', 'Event bubbling means an event propagates upward from the target element to the document root.'),
  (set_id, 'MCQ', 'Which hook is used to access Context in functional React components?', '["useState", "useContext", "useEffect", "useReducer"]'::jsonb, 'useContext', 'The useContext hook lets you subscribe to React context without introducing nesting.'),
  (set_id, 'MCQ', 'What is the purpose of a "key" prop in a React list?', '["To uniquely identify elements for efficient re-rendering", "To set the CSS id", "To define the index", "To secure the component"]'::jsonb, 'To uniquely identify elements for efficient re-rendering', 'Keys help React identify which items have changed, been added, or been removed in a list.'),
  (set_id, 'MCQ', 'Which CSS unit is relative to the font-size of the root element?', '["em", "rem", "px", "vh"]'::jsonb, 'rem', 'The ''rem'' unit stands for "root em" and scales according to the <html> element''s font size.'),
  (set_id, 'MCQ', 'What does the JavaScript "fetch" API return?', '["JSON data", "A Promise", "A callback", "An XML document"]'::jsonb, 'A Promise', 'The fetch() method returns a Promise that resolves to the Response to that request.');

  -- D3
  INSERT INTO public.screening_question_sets (domain_id, difficulty_level, version, is_active) VALUES (fe_id, 3, 1, true) RETURNING id INTO set_id;
  INSERT INTO public.screening_questions (set_id, type, content, options, correct_answer, explanation) VALUES
  (set_id, 'MCQ', 'What is Server-Side Rendering (SSR) in the context of Next.js?', '["Rendering the page in the browser using JavaScript", "Generating HTML on the server for each request", "Generating HTML at build time", "Caching assets on a CDN"]'::jsonb, 'Generating HTML on the server for each request', 'SSR generates the full HTML for a page on the server in response to a request, before sending it to the client.'),
  (set_id, 'MCQ', 'What is the primary benefit of Code Splitting?', '["It encrypts the code", "It reduces the initial load time by sending only necessary JavaScript", "It makes the code more readable", "It prevents XSS attacks"]'::jsonb, 'It reduces the initial load time by sending only necessary JavaScript', 'Code splitting allows you to split your code into various bundles which can then be loaded on demand.'),
  (set_id, 'MCQ', 'How do you prevent excessive re-renders in a React component?', '["Using useState", "Using React.memo and useMemo", "Removing CSS", "Using class components instead"]'::jsonb, 'Using React.memo and useMemo', 'React.memo memoizes the component itself, while useMemo memoizes the result of a calculation.'),
  (set_id, 'MCQ', 'What is a Service Worker used for?', '["Managing database queries", "Background sync, push notifications, and offline caching", "Rendering UI components", "Server-side routing"]'::jsonb, 'Background sync, push notifications, and offline caching', 'Service workers act as proxy servers that sit between web applications, the browser, and the network.'),
  (set_id, 'MCQ', 'What does the "z-index" property in CSS control?', '["The zoom level of an element", "The stack order of positioned elements", "The opacity of an element", "The scale transformation"]'::jsonb, 'The stack order of positioned elements', 'Elements with a higher z-index overlap elements with a lower one, but only if they are positioned.'),
  (set_id, 'MCQ', 'What is a common technique to mitigate Cross-Site Scripting (XSS)?', '["Disabling JavaScript", "Using strong passwords", "Sanitizing user input and escaping outputs", "Using HTTPS"]'::jsonb, 'Sanitizing user input and escaping outputs', 'Sanitization ensures any injected scripts are rendered as text rather than executed by the browser.'),
  (set_id, 'MCQ', 'What is the critical rendering path?', '["The sequence of steps the browser goes through to convert HTML, CSS, and JS into pixels on the screen", "The route a user takes through an application", "The API endpoints called during initial load", "The path to the main JavaScript bundle"]'::jsonb, 'The sequence of steps the browser goes through to convert HTML, CSS, and JS into pixels on the screen', 'Optimizing this path is key to improving perceived page load times.');

  -- 4. Backend Development
  -- D1
  INSERT INTO public.screening_question_sets (domain_id, difficulty_level, version, is_active) VALUES (be_id, 1, 1, true) RETURNING id INTO set_id;
  INSERT INTO public.screening_questions (set_id, type, content, options, correct_answer, explanation) VALUES
  (set_id, 'MCQ', 'What is Node.js?', '["A front-end framework", "A JavaScript runtime built on Chrome''s V8 engine", "A relational database", "A CSS preprocessor"]'::jsonb, 'A JavaScript runtime built on Chrome''s V8 engine', 'Node.js allows developers to run JavaScript on the server side.'),
  (set_id, 'MCQ', 'What does API stand for?', '["Application Programming Interface", "Advanced Protocol Integration", "Automated Process Interface", "Application Process Integration"]'::jsonb, 'Application Programming Interface', 'APIs define methods of communication between various software components.'),
  (set_id, 'MCQ', 'Which of these is a popular Node.js web framework?', '["React", "Express", "Django", "Laravel"]'::jsonb, 'Express', 'Express is a minimal and flexible Node.js web application framework.'),
  (set_id, 'MCQ', 'What is the default port for HTTP?', '["443", "21", "80", "8080"]'::jsonb, '80', 'HTTP relies on port 80, while HTTPS uses port 443.'),
  (set_id, 'MCQ', 'What is NPM?', '["Network Protocol Manager", "Node Package Manager", "New Programming Model", "Node Process Monitor"]'::jsonb, 'Node Package Manager', 'NPM is the default package manager for the Node.js environment.'),
  (set_id, 'MCQ', 'Which HTTP status code indicates a successful request?', '["404", "500", "301", "200"]'::jsonb, '200', 'Status 200 OK means the request succeeded.'),
  (set_id, 'MCQ', 'What does CRUD stand for?', '["Create, Read, Update, Delete", "Copy, Rename, Undo, Deploy", "Compile, Run, Use, Destroy", "Create, Route, Upload, Download"]'::jsonb, 'Create, Read, Update, Delete', 'CRUD represents the four basic operations of persistent storage.');

  -- D2
  INSERT INTO public.screening_question_sets (domain_id, difficulty_level, version, is_active) VALUES (be_id, 2, 1, true) RETURNING id INTO set_id;
  INSERT INTO public.screening_questions (set_id, type, content, options, correct_answer, explanation) VALUES
  (set_id, 'MCQ', 'What is Middleware in the context of Express.js?', '["The database layer", "Functions that have access to the request and response objects", "The front-end client", "The operating system"]'::jsonb, 'Functions that have access to the request and response objects', 'Middleware functions can execute code, modify requests/responses, and end the cycle.'),
  (set_id, 'MCQ', 'What is the difference between Authentication and Authorization?', '["They are the same thing", "Authentication verifies who you are, Authorization verifies what you can do", "Authorization verifies who you are, Authentication verifies what you can do", "Authentication is for databases, Authorization is for APIs"]'::jsonb, 'Authentication verifies who you are, Authorization verifies what you can do', 'Authentication is about identity, Authorization is about permissions.'),
  (set_id, 'MCQ', 'What is an ORM?', '["Object-Relational Mapping tool", "Origin Resource Manager", "Online Routing Mechanism", "Object Request Middleware"]'::jsonb, 'Object-Relational Mapping tool', 'An ORM lets you interact with your database using your preferred programming language rather than SQL.'),
  (set_id, 'MCQ', 'Why are database indexes used?', '["To compress data", "To encrypt data", "To speed up data retrieval operations", "To enforce foreign keys"]'::jsonb, 'To speed up data retrieval operations', 'Indexes improve the speed of data retrieval operations at the cost of additional storage and write time.'),
  (set_id, 'MCQ', 'What is a RESTful API?', '["An API that uses GraphQL", "An API that conforms to Representational State Transfer architectural constraints", "An API that requires SOAP", "An API that only returns HTML"]'::jsonb, 'An API that conforms to Representational State Transfer architectural constraints', 'RESTful APIs use HTTP methods explicitly and are stateless.'),
  (set_id, 'MCQ', 'What is the purpose of Docker?', '["To format code", "To containerize applications and their dependencies", "To compile JavaScript", "To manage databases"]'::jsonb, 'To containerize applications and their dependencies', 'Docker packages software into standardized units for development, shipment and deployment.'),
  (set_id, 'MCQ', 'Which HTTP method should be idempotent according to REST standards?', '["POST", "PUT", "PATCH", "None"]'::jsonb, 'PUT', 'PUT replaces the entire resource, so making the same request multiple times has the same effect as making it once.');

  -- D3
  INSERT INTO public.screening_question_sets (domain_id, difficulty_level, version, is_active) VALUES (be_id, 3, 1, true) RETURNING id INTO set_id;
  INSERT INTO public.screening_questions (set_id, type, content, options, correct_answer, explanation) VALUES
  (set_id, 'MCQ', 'What is the CAP Theorem?', '["A principle that a distributed system can only provide two of: Consistency, Availability, Partition Tolerance", "A rule for CSS positioning", "A database normalization standard", "An encryption algorithm"]'::jsonb, 'A principle that a distributed system can only provide two of: Consistency, Availability, Partition Tolerance', 'CAP Theorem states you must trade-off between Consistency, Availability, and Partition Tolerance in distributed networks.'),
  (set_id, 'MCQ', 'How does Redis differ from PostgreSQL?', '["Redis is relational, PostgreSQL is NoSQL", "Redis is an in-memory key-value store, PostgreSQL is an on-disk relational database", "Redis is slower but holds more data", "They are the same"]'::jsonb, 'Redis is an in-memory key-value store, PostgreSQL is an on-disk relational database', 'Redis is typically used for caching, while Postgres is used for persistent, structured data.'),
  (set_id, 'MCQ', 'What is the N+1 query problem?', '["A syntax error in SQL", "Executing one query to fetch a list, then N additional queries to fetch related data for each item", "When a database cluster has too many nodes", "A caching invalidation issue"]'::jsonb, 'Executing one query to fetch a list, then N additional queries to fetch related data for each item', 'The N+1 problem causes severe performance issues and is typically solved by eager loading relations.'),
  (set_id, 'MCQ', 'What is horizontal scaling?', '["Upgrading the server''s CPU and RAM", "Adding more servers/instances to the pool", "Optimizing database queries", "Compressing HTTP responses"]'::jsonb, 'Adding more servers/instances to the pool', 'Horizontal scaling (scaling out) involves adding more machines to your network, unlike vertical scaling (scaling up).'),
  (set_id, 'MCQ', 'In message queues like RabbitMQ, what is a Dead Letter Exchange (DLX)?', '["A place where successfully processed messages go", "A routing mechanism for undeliverable or rejected messages", "The main queue for high priority messages", "A security feature to drop spam messages"]'::jsonb, 'A routing mechanism for undeliverable or rejected messages', 'A DLX safely captures messages that couldn''t be processed so they aren''t lost.'),
  (set_id, 'MCQ', 'What is the purpose of connection pooling in databases?', '["To encrypt connections", "To maintain a cache of database connections to reuse, reducing overhead", "To allow multiple databases to sync", "To block malicious IPs"]'::jsonb, 'To maintain a cache of database connections to reuse, reducing overhead', 'Opening new connections is expensive; a pool reuses existing connections.'),
  (set_id, 'MCQ', 'What is a race condition?', '["When two processes try to access shared resources at the same time resulting in unexpected behavior", "A fast sorting algorithm", "When a server handles too many requests", "A network latency issue"]'::jsonb, 'When two processes try to access shared resources at the same time resulting in unexpected behavior', 'Race conditions require synchronization mechanisms like mutexes or locks to prevent data corruption.');

  -- 5. Cybersecurity
  -- D1
  INSERT INTO public.screening_question_sets (domain_id, difficulty_level, version, is_active) VALUES (cs_id, 1, 1, true) RETURNING id INTO set_id;
  INSERT INTO public.screening_questions (set_id, type, content, options, correct_answer, explanation) VALUES
  (set_id, 'MCQ', 'What does HTTPS stand for?', '["HyperText Transfer Protocol Secure", "HyperText Transfer Protocol Standard", "Hyperlink Transfer Protocol Secure", "High-level Text Transfer Protocol"]'::jsonb, 'HyperText Transfer Protocol Secure', 'HTTPS encrypts the data sent between your browser and the website.'),
  (set_id, 'MCQ', 'What is phishing?', '["A type of firewall", "A social engineering attack to steal credentials", "A database query technique", "A network protocol"]'::jsonb, 'A social engineering attack to steal credentials', 'Phishing attackers masquerade as a trusted entity to dupe a victim into opening an email or message.'),
  (set_id, 'MCQ', 'What is a VPN?', '["Virtual Private Network", "Virtual Public Node", "Visual Processing Node", "Verified Private Network"]'::jsonb, 'Virtual Private Network', 'A VPN creates a secure, encrypted connection over a less secure network, such as the internet.'),
  (set_id, 'MCQ', 'What is the purpose of an antivirus program?', '["To speed up the computer", "To detect and remove malicious software", "To defragment the hard drive", "To manage network traffic"]'::jsonb, 'To detect and remove malicious software', 'Antivirus software is designed to detect, prevent, and take action to disarm or remove malicious software.'),
  (set_id, 'MCQ', 'What is two-factor authentication (2FA)?', '["Using two passwords", "Requiring two forms of identification to access an account", "Logging in from two devices", "A type of encryption"]'::jsonb, 'Requiring two forms of identification to access an account', '2FA requires a user to provide two different authentication factors to verify themselves.'),
  (set_id, 'MCQ', 'What does malware stand for?', '["Malfunctioning hardware", "Malicious software", "Multipurpose ware", "Mainframe wire"]'::jsonb, 'Malicious software', 'Malware is any software intentionally designed to cause damage to a computer, server, client, or network.'),
  (set_id, 'MCQ', 'Why is reusing passwords dangerous?', '["It wastes memory", "If one site is breached, attackers can access your other accounts", "It slows down the login process", "It is against the law"]'::jsonb, 'If one site is breached, attackers can access your other accounts', 'Credential stuffing attacks use passwords leaked from one breach to access accounts on other sites.');

  -- D2
  INSERT INTO public.screening_question_sets (domain_id, difficulty_level, version, is_active) VALUES (cs_id, 2, 1, true) RETURNING id INTO set_id;
  INSERT INTO public.screening_questions (set_id, type, content, options, correct_answer, explanation) VALUES
  (set_id, 'MCQ', 'What is Cross-Site Scripting (XSS)?', '["Injecting malicious SQL into a database", "Injecting malicious scripts into web pages viewed by other users", "Flooding a server with traffic", "Intercepting network packets"]'::jsonb, 'Injecting malicious scripts into web pages viewed by other users', 'XSS allows an attacker to execute malicious scripts in the victim''s browser.'),
  (set_id, 'MCQ', 'What is a DDOS attack?', '["Distributed Denial of Service", "Direct Data Overwrite System", "Dynamic Domain Operating System", "Data Destruction and Obfuscation Script"]'::jsonb, 'Distributed Denial of Service', 'A DDoS attack attempts to overwhelm a network, service, or server with a flood of internet traffic.'),
  (set_id, 'MCQ', 'What is the difference between symmetric and asymmetric encryption?', '["Symmetric uses one key for encryption/decryption; asymmetric uses a public/private key pair", "Symmetric is for hardware, asymmetric for software", "They are the same", "Asymmetric is much faster"]'::jsonb, 'Symmetric uses one key for encryption/decryption; asymmetric uses a public/private key pair', 'Asymmetric encryption is generally slower but allows for secure key exchange over untrusted networks.'),
  (set_id, 'MCQ', 'What does the Principle of Least Privilege mean?', '["Giving users minimal hardware", "Granting users only the access rights necessary to perform their jobs", "Making passwords as short as possible", "Using the weakest encryption"]'::jsonb, 'Granting users only the access rights necessary to perform their jobs', 'This principle minimizes the potential damage from compromised accounts.'),
  (set_id, 'MCQ', 'What is a firewall?', '["A physical wall protecting servers", "A network security system that monitors and controls incoming and outgoing network traffic", "An antivirus program", "A load balancer"]'::jsonb, 'A network security system that monitors and controls incoming and outgoing network traffic', 'Firewalls establish a barrier between a trusted internal network and untrusted external networks.'),
  (set_id, 'MCQ', 'What is hashing used for in password storage?', '["To encrypt passwords so they can be decrypted later", "To convert passwords into an irreversible fixed-length string", "To compress passwords", "To transmit passwords securely over the network"]'::jsonb, 'To convert passwords into an irreversible fixed-length string', 'Hashing ensures that even if a database is breached, the original passwords are not immediately exposed.'),
  (set_id, 'MCQ', 'What is Social Engineering?', '["Manipulating people so they give up confidential information", "Building secure networks", "Coding secure applications", "Analyzing social media data"]'::jsonb, 'Manipulating people so they give up confidential information', 'Social engineering targets human vulnerabilities rather than technical vulnerabilities.');

  -- D3
  INSERT INTO public.screening_question_sets (domain_id, difficulty_level, version, is_active) VALUES (cs_id, 3, 1, true) RETURNING id INTO set_id;
  INSERT INTO public.screening_questions (set_id, type, content, options, correct_answer, explanation) VALUES
  (set_id, 'MCQ', 'What is a Buffer Overflow attack?', '["When an application receives more data than it can handle, causing it to overwrite adjacent memory", "When a database receives too many queries", "When a network buffer is full and drops packets", "When a hard drive runs out of space"]'::jsonb, 'When an application receives more data than it can handle, causing it to overwrite adjacent memory', 'Attackers can use buffer overflows to execute arbitrary code or crash the system.'),
  (set_id, 'MCQ', 'How does a Man-in-the-Middle (MitM) attack work?', '["By guessing a user''s password", "By secretly intercepting and possibly altering communications between two parties", "By injecting SQL code", "By flooding the server"]'::jsonb, 'By secretly intercepting and possibly altering communications between two parties', 'MitM attacks intercept communication to steal data or alter messages.'),
  (set_id, 'MCQ', 'What is the purpose of a Salt in password hashing?', '["To make the hash shorter", "To add random data to the password before hashing to defend against rainbow table attacks", "To encrypt the hash", "To speed up the hashing process"]'::jsonb, 'To add random data to the password before hashing to defend against rainbow table attacks', 'Salts ensure that two identical passwords hash to different values, defeating pre-computed rainbow tables.'),
  (set_id, 'MCQ', 'What is Cross-Site Request Forgery (CSRF)?', '["Tricking a victim into submitting a malicious request on a site where they are authenticated", "Injecting scripts into a webpage", "Stealing a user''s cookies directly", "Bypassing firewall rules"]'::jsonb, 'Tricking a victim into submitting a malicious request on a site where they are authenticated', 'CSRF exploits the trust that a site has in a user''s browser by forcing it to execute unwanted actions.'),
  (set_id, 'MCQ', 'Which model describes information security using Confidentiality, Integrity, and Availability?', '["The OSI Model", "The CIA Triad", "The STRIDE Model", "The MITRE ATT&CK Framework"]'::jsonb, 'The CIA Triad', 'The CIA Triad is the foundational model for information security policies.'),
  (set_id, 'MCQ', 'What is a Zero-Day vulnerability?', '["A vulnerability that takes zero days to patch", "A flaw unknown to the software maker, meaning there is zero days of protection", "A bug that causes no damage", "A virus that deletes everything at midnight"]'::jsonb, 'A flaw unknown to the software maker, meaning there is zero days of protection', 'Zero-days are particularly dangerous because no patch exists at the time of discovery.'),
  (set_id, 'MCQ', 'What is Penetration Testing?', '["Testing network speed", "An authorized simulated cyberattack to evaluate the security of a system", "Testing physical server locks", "Reviewing code for formatting errors"]'::jsonb, 'An authorized simulated cyberattack to evaluate the security of a system', 'Pen tests proactively identify vulnerabilities before malicious attackers can exploit them.');

  -- 6. Data Science
  -- D1
  INSERT INTO public.screening_question_sets (domain_id, difficulty_level, version, is_active) VALUES (ds_id, 1, 1, true) RETURNING id INTO set_id;
  INSERT INTO public.screening_questions (set_id, type, content, options, correct_answer, explanation) VALUES
  (set_id, 'MCQ', 'Which programming language is most widely used in Data Science?', '["Python", "JavaScript", "C++", "PHP"]'::jsonb, 'Python', 'Python is the industry standard due to libraries like pandas, NumPy, and Scikit-learn.'),
  (set_id, 'MCQ', 'What is a DataFrame in pandas?', '["A 2-dimensional labeled data structure with columns of potentially different types", "A machine learning model", "A database connection", "A type of graph"]'::jsonb, 'A 2-dimensional labeled data structure with columns of potentially different types', 'A DataFrame is essentially a table of data, similar to a spreadsheet or SQL table.'),
  (set_id, 'MCQ', 'What does the term "mean" refer to in statistics?', '["The middle value", "The most frequent value", "The average value", "The difference between highest and lowest"]'::jsonb, 'The average value', 'The mean is calculated by summing all values and dividing by the number of values.'),
  (set_id, 'MCQ', 'Which library is commonly used for data visualization in Python?', '["NumPy", "Matplotlib", "Scikit-learn", "TensorFlow"]'::jsonb, 'Matplotlib', 'Matplotlib is the foundational plotting library for Python.'),
  (set_id, 'MCQ', 'What is CSV an abbreviation for?', '["Comma-Separated Values", "Computer System Variables", "Common Source Validation", "Centralized Secure Vault"]'::jsonb, 'Comma-Separated Values', 'CSV is a simple text format for storing tabular data.'),
  (set_id, 'MCQ', 'What is the purpose of Data Cleaning?', '["To format code", "To identify and correct inaccurate or incomplete data", "To delete old databases", "To encrypt data"]'::jsonb, 'To identify and correct inaccurate or incomplete data', 'Data cleaning is an essential preprocessing step because garbage data leads to garbage models.'),
  (set_id, 'MCQ', 'What does SQL stand for?', '["Structured Query Language", "Simple Question Language", "System Query Logic", "Standard Quantified Language"]'::jsonb, 'Structured Query Language', 'SQL is the standard language for relational database management and data manipulation.');

  -- D2
  INSERT INTO public.screening_question_sets (domain_id, difficulty_level, version, is_active) VALUES (ds_id, 2, 1, true) RETURNING id INTO set_id;
  INSERT INTO public.screening_questions (set_id, type, content, options, correct_answer, explanation) VALUES
  (set_id, 'MCQ', 'What is standard deviation?', '["A measure of the amount of variation or dispersion of a set of values", "The sum of all values", "The middle value in a sorted list", "The most frequent value"]'::jsonb, 'A measure of the amount of variation or dispersion of a set of values', 'A low standard deviation means data points tend to be close to the mean, while a high one means they are spread out.'),
  (set_id, 'MCQ', 'What is a p-value in hypothesis testing?', '["The probability of obtaining test results at least as extreme as the observed results, assuming the null hypothesis is true", "The accuracy of the model", "The ratio of true positives to false positives", "The correlation coefficient"]'::jsonb, 'The probability of obtaining test results at least as extreme as the observed results, assuming the null hypothesis is true', 'A low p-value (typically ≤ 0.05) indicates strong evidence against the null hypothesis.'),
  (set_id, 'MCQ', 'Which method is used to handle missing data?', '["Imputation", "Gradient Descent", "Normalization", "Clustering"]'::jsonb, 'Imputation', 'Imputation replaces missing data with substituted values, like the mean or median.'),
  (set_id, 'MCQ', 'What is feature scaling?', '["Adding more features to a dataset", "Normalizing the range of independent variables or features of data", "Removing irrelevant features", "Multiplying features together"]'::jsonb, 'Normalizing the range of independent variables or features of data', 'Scaling ensures that features with larger magnitudes do not dominate the learning algorithm.'),
  (set_id, 'MCQ', 'What is a correlation coefficient?', '["A statistical measure of the strength of the relationship between the relative movements of two variables", "The rate of learning in a neural network", "The number of clusters in K-Means", "The error rate of a regression model"]'::jsonb, 'A statistical measure of the strength of the relationship between the relative movements of two variables', 'Correlation ranges from -1 to +1, indicating negative or positive relationships.'),
  (set_id, 'MCQ', 'What does ETL stand for?', '["Extract, Transform, Load", "Evaluate, Train, Learn", "Execute, Test, Launch", "Export, Translate, Link"]'::jsonb, 'Extract, Transform, Load', 'ETL is the process of extracting data from systems, transforming it into a clean structure, and loading it into a data warehouse.'),
  (set_id, 'MCQ', 'What is A/B testing?', '["Testing code for bugs", "A randomized experiment with two variants, A and B, to determine which performs better", "Testing a database''s backup system", "Testing API endpoints"]'::jsonb, 'A randomized experiment with two variants, A and B, to determine which performs better', 'A/B testing is widely used in tech to make data-driven product decisions.');

  -- D3
  INSERT INTO public.screening_question_sets (domain_id, difficulty_level, version, is_active) VALUES (ds_id, 3, 1, true) RETURNING id INTO set_id;
  INSERT INTO public.screening_questions (set_id, type, content, options, correct_answer, explanation) VALUES
  (set_id, 'MCQ', 'What is the Central Limit Theorem?', '["As the sample size increases, the sampling distribution of the mean approaches a normal distribution, regardless of the population distribution", "All data must be centralized", "There is a limit to how much data can be processed centrally", "The median is always equal to the mean"]'::jsonb, 'As the sample size increases, the sampling distribution of the mean approaches a normal distribution, regardless of the population distribution', 'This theorem is foundational because it allows us to use normal distribution models even if the underlying data isn''t normal.'),
  (set_id, 'MCQ', 'What is regularization (e.g., L1, L2) used for?', '["To speed up training", "To prevent overfitting by adding a penalty term to the loss function", "To increase model complexity", "To clean missing data"]'::jsonb, 'To prevent overfitting by adding a penalty term to the loss function', 'L1 adds an absolute value penalty (Lasso), and L2 adds a squared magnitude penalty (Ridge).'),
  (set_id, 'MCQ', 'In Time Series Analysis, what does ARIMA stand for?', '["AutoRegressive Integrated Moving Average", "Automatic Random Iterative Machine Algorithm", "Analysis of Random Independent Metric Averages", "Automated Regression Integrated Matrix Algebra"]'::jsonb, 'AutoRegressive Integrated Moving Average', 'ARIMA is a classic statistical model for analyzing and forecasting time series data.'),
  (set_id, 'MCQ', 'What is Principal Component Analysis (PCA) used for?', '["Classification", "Regression", "Dimensionality Reduction", "Clustering"]'::jsonb, 'Dimensionality Reduction', 'PCA simplifies data complexity by transforming variables into a smaller number of uncorrelated components.'),
  (set_id, 'MCQ', 'What is the curse of dimensionality?', '["The phenomenon where data becomes too large to fit in memory", "Various phenomena that arise when analyzing data in high-dimensional spaces that do not occur in low-dimensional settings", "When a neural network has too many layers", "When a SQL query joins too many tables"]'::jsonb, 'Various phenomena that arise when analyzing data in high-dimensional spaces that do not occur in low-dimensional settings', 'In high dimensions, all data points become sparse and equidistant, making clustering and distance metrics less meaningful.'),
  (set_id, 'MCQ', 'What is a bias-variance tradeoff?', '["The conflict in trying to simultaneously minimize bias and variance, which prevents supervised learning algorithms from generalizing beyond their training set", "Choosing between a biased human and varying data", "The decision to add more layers vs more neurons", "A financial model concept"]'::jsonb, 'The conflict in trying to simultaneously minimize bias and variance, which prevents supervised learning algorithms from generalizing beyond their training set', 'High bias causes underfitting; high variance causes overfitting. Models must find a balance.'),
  (set_id, 'MCQ', 'What is SMOTE used for?', '["Text analysis", "Oversampling the minority class in an imbalanced dataset", "Clustering spatial data", "Optimizing neural network weights"]'::jsonb, 'Oversampling the minority class in an imbalanced dataset', 'SMOTE synthesizes new examples for the minority class to help the model learn better decision boundaries.');

END $$;
